[package]
name = "xtask-core"
version = "0.9.0"
edition = "2024"

[dependencies]
log = "0.4.28"
strum = "0.27.2"
tracel-xtask = { path = "../crates/tracel-xtask", version = "=5.3.0", features = [
    "aws-container",
    "aws-secrets",
    "build",
    "bump",
    "check",
    "clean",
    "compile",
    "coverage",
    "dependencies",
    "doc",
    "docker-compose",
    "fix",
    "gcp-container",
    "gcp-secrets",
    "host",
    "icons",
    "infra",
    "publish",
    "test",
    "validate",
    "vulnerabilities",
] }
