[workspace]
resolver = "2"
members = [
    "crates/*",
    "xtask-core",
]

[workspace.package]
edition = "2024"
version = "5.2.0"
license = "MIT OR Apache-2.0"
readme = "README.md"

[workspace.dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.39", features = ["derive"] }
ctrlc = "3.4.7"
dotenvy = "0.15.7"
env_logger = "0.11.8"
home = "0.5.12"
ico = "0.5.0"
image-rs = { package = "image", version = "=0.25.9", default-features = false }
inquire = "0.9.3"
log = "0.4.27"
owo-colors = "4.2.3"
proc-macro2 = "1.0.95"
quote = "1.0.40"
rand = "0.9.1"
regex = "1.11.1"
resvg = "0.48.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
strum = {version = "0.27.1", features = ["derive"]}
syn = {version = "~2.0" , features = ["full"]}
time = { version = "0.3.47", features = ["parsing", "formatting"] }
toml = { version = "0.9.8", default-features = false, features = ["display", "parse", "serde"] }
ureq = { version = "3.2", features = ["_tls", "json"] }
zip = "6.0.0"

# for tests
rstest = "0.25.0"
serial_test = "3.2.0"
tempfile = "3.23.0"

[profile.dev]
debug = 0 # Speed up compilation time and not necessary.
