use super::*;

fn create_test_workspace(path: &Path, xtask_package: &str) {
    fs::create_dir_all(path.join("xtask/src")).expect("xtask source directory should be created");
    fs::write(
        path.join("Cargo.toml"),
        r#"[workspace]
members = ["xtask"]
resolver = "3"

[workspace.dependencies]
test-dependency = { version = "1.0.0", path = "unused-before-sync" }
"#,
    )
    .expect("workspace manifest should be written");
    fs::write(
        path.join("xtask/Cargo.toml"),
        format!(
            r#"[package]
name = "{xtask_package}"
version = "0.1.0"
edition = "2024"

[dependencies]
test-dependency.workspace = true
"#
        ),
    )
    .expect("xtask manifest should be written");
    fs::write(path.join("xtask/src/main.rs"), "fn main() {}\n")
        .expect("xtask source should be written");
    fs::write(
        path.join("Cargo.lock"),
        format!(
            r#"# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "test-dependency"
version = "1.0.0"

[[package]]
name = "{xtask_package}"
version = "0.1.0"
dependencies = [
 "test-dependency",
]
"#
        ),
    )
    .expect("stale workspace lockfile should be written");
}

fn create_test_dependencies_manifest(path: &Path) {
    fs::create_dir_all(path.join("deps/test-dependency/src"))
        .expect("test dependency source directory should be created");
    fs::write(
        path.join("Dependencies.toml"),
        r#"[workspace.dependencies]
test-dependency = { version = "2.0.0", path = "deps/test-dependency" }
"#,
    )
    .expect("dependencies manifest should be written");
    fs::write(
        path.join("deps/test-dependency/Cargo.toml"),
        r#"[package]
name = "test-dependency"
version = "2.0.0"
edition = "2024"
"#,
    )
    .expect("test dependency manifest should be written");
    fs::write(path.join("deps/test-dependency/src/lib.rs"), "")
        .expect("test dependency source should be written");
}

fn assert_lockfile_updated_without_building(workspace_root: &Path) {
    let lockfile = fs::read_to_string(workspace_root.join("Cargo.lock"))
        .expect("workspace lockfile should be created");
    assert!(lockfile.contains("name = \"test-dependency\""));
    assert!(lockfile.contains("version = \"2.0.0\""));
    assert!(!lockfile.contains("version = \"1.0.0\""));
    assert!(!workspace_root.join("target").exists());
}

fn workspace(name: &str) -> Workspace {
    Workspace {
        git_root: PathBuf::from("repository"),
        path: PathBuf::from(name),
        dir_name: name.to_string(),
        xtask_bin: format!("xtask-{name}"),
        xtask: XtaskInvocation::WorkspaceMember {
            package: "xtask".to_string(),
        },
        toolchain: None,
    }
}

fn select<'a>(subrepos: &'a [Workspace], selector: &str) -> Result<&'a str, String> {
    select_subrepo_workspace_from_list(subrepos, selector).map(|ws| ws.dir_name.as_str())
}

#[test]
fn skill_invocation_is_detected_as_a_wrapper_special_command() {
    assert!(is_skill_invocation(&[OsString::from("+skill")]));
}

#[test]
fn update_invocation_is_detected_as_a_wrapper_special_command() {
    assert!(is_update_invocation(&[OsString::from("+update")]));
}

#[test]
fn sync_invocation_is_detected_as_a_wrapper_special_command() {
    assert!(is_sync_invocation(&[OsString::from("+sync")]));
}

#[test]
fn clean_invocation_is_detected_as_a_wrapper_special_command() {
    assert!(is_clean_invocation(&[OsString::from("+clean")]));
}

#[test]
fn skill_invocation_must_be_the_first_argument() {
    assert!(!is_skill_invocation(&[
        OsString::from("check"),
        OsString::from("+skill")
    ]));
}

#[test]
fn update_invocation_must_be_the_first_argument() {
    assert!(!is_update_invocation(&[
        OsString::from("check"),
        OsString::from("+update")
    ]));
}

#[test]
fn sync_invocation_must_be_the_first_argument() {
    assert!(!is_sync_invocation(&[
        OsString::from("check"),
        OsString::from("+sync")
    ]));
}

#[test]
fn clean_invocation_must_be_the_first_argument() {
    assert!(!is_clean_invocation(&[
        OsString::from("check"),
        OsString::from("+clean")
    ]));
}

#[test]
fn persistent_target_directory_is_external_and_stable() {
    let repository = tempfile::tempdir().expect("temporary repository should be created");
    let cache = tempfile::tempdir().expect("temporary cache should be created");
    let workspace_path = repository.path().to_path_buf();
    let mut workspace = workspace("root");
    workspace.git_root = repository.path().to_path_buf();
    workspace.path = workspace_path.clone();
    let repository_identity = repository_identity(repository.path());

    let first = persistent_target_dir_under(cache.path(), &repository_identity, &workspace);
    let second = persistent_target_dir_under(cache.path(), &repository_identity, &workspace);

    assert_eq!(first, second);
    assert_eq!(
        first,
        cache
            .path()
            .join("v1")
            .join(&repository_identity.parent)
            .join(&repository_identity.name)
            .join("xtask")
            .join("default")
    );
    assert!(!first.starts_with(&workspace_path));
}

#[test]
fn persistent_target_directory_isolated_by_workspace_and_toolchain() {
    let repository = tempfile::tempdir().expect("temporary repository should be created");
    let cache = tempfile::tempdir().expect("temporary cache should be created");
    let mut backend = workspace("backend");
    backend.git_root = repository.path().to_path_buf();
    backend.path = repository.path().join("backend");
    fs::create_dir_all(&backend.path).expect("backend workspace should be created");

    let mut frontend = workspace("frontend");
    frontend.git_root = repository.path().to_path_buf();
    frontend.path = repository.path().join("frontend");
    fs::create_dir_all(&frontend.path).expect("frontend workspace should be created");

    let mut nightly_backend = backend.clone();
    nightly_backend.toolchain = Some(ToolchainOverride::Nightly);
    let repository_identity = repository_identity(repository.path());

    let backend_target = persistent_target_dir_under(cache.path(), &repository_identity, &backend);
    let frontend_target =
        persistent_target_dir_under(cache.path(), &repository_identity, &frontend);
    let nightly_target =
        persistent_target_dir_under(cache.path(), &repository_identity, &nightly_backend);

    assert_ne!(backend_target, frontend_target);
    assert_ne!(backend_target, nightly_target);
    assert!(backend_target.ends_with(Path::new("backend").join("xtask").join("default")));
    assert!(frontend_target.ends_with(Path::new("frontend").join("xtask").join("default")));
    assert_eq!(nightly_target.file_name(), Some(OsStr::new("nightly")));
}

#[test]
fn repository_identity_uses_clone_parent_and_directory_names() {
    let root = tempfile::tempdir().expect("temporary root should be created");
    let git_root = root.path().join("namespace/repository");
    fs::create_dir_all(&git_root).expect("git root should be created");

    let identity = repository_identity(&git_root);

    assert_eq!(identity.parent, "namespace");
    assert_eq!(identity.name, "repository");
}

#[test]
fn clean_xtask_target_runs_cargo_clean_for_external_directory() {
    let repository = tempfile::tempdir().expect("temporary repository should be created");
    let target_root = tempfile::tempdir().expect("temporary target root should be created");
    let target = target_root.path().join("cargo-target");
    fs::create_dir_all(repository.path().join("src"))
        .expect("package source directory should be created");
    fs::write(
        repository.path().join("Cargo.toml"),
        r#"[package]
name = "clean-test"
version = "0.1.0"
edition = "2024"
"#,
    )
    .expect("package manifest should be written");
    fs::write(repository.path().join("src/main.rs"), "fn main() {}\n")
        .expect("package source should be written");
    let build_status = Command::new("cargo")
        .arg("check")
        .arg("--quiet")
        .arg("--target-dir")
        .arg(&target)
        .current_dir(repository.path())
        .status()
        .expect("cargo check should execute");
    assert!(build_status.success());
    let artifact = target.join("debug/cached-xtask");
    fs::create_dir_all(artifact.parent().expect("artifact should have a parent"))
        .expect("target profile directory should be created");
    fs::write(&artifact, "cached xtask").expect("cached artifact should be written");
    let mut workspace = workspace("root");
    workspace.path = repository.path().to_path_buf();

    clean_xtask_target(&workspace, &target).expect("xtask cache clean should succeed");

    assert!(!artifact.exists());
}

#[test]
fn skill_text_contains_agent_operating_cues() {
    let text = skill::text();

    assert!(text.contains("Tracel xtask agent skill"));
    assert!(text.contains("xtask [+nightly|+n] [:<subrepo>|:all] [<xtask args...>]"));
    assert!(text.contains("xtask [+nightly|+n] +clean"));
    assert!(text.contains("Wrapper modifiers and special commands"));
    assert!(text.contains("`+clean` runs `cargo clean --target-dir <persistent-target>`"));
    assert!(text.contains("accepts neither additional"));
    assert!(text.contains("arguments nor subrepo selectors"));
    assert!(text.contains("Persistent xtask cache"));
    assert!(text.contains("Repository-local xtasks always compile into an external Cargo target"));
    assert!(text.contains("<clone-parent>/<repository>"));
    assert!(text.contains("/src/github/tracel/xtask"));
    assert!(text.contains("`default` means no explicit Rust toolchain override"));
    assert!(text.contains("ordinary project `cargo clean` does not touch"));
    assert!(text.contains("xtask +n +clean"));
    assert!(text.contains("xtask +update"));
    assert!(text.contains("xtask +sync"));
    assert!(text.contains("without running a repository-local xtask command"));
    assert!(text.contains("Cargo.lock"));
    assert!(text.contains("XTASK_CLI=1"));
    assert!(text.contains("Testing model"));
    assert!(
        text.contains("Unit tests are tests compiled with library, binary, and example targets")
    );
    assert!(text.contains("Integration tests are crate-level test targets"));
    assert!(text.contains("Environment management"));
    assert!(text.contains("stag2"));
    assert!(text.contains("dotenvy::from_path"));
    assert!(text.contains("Dependency synchronization"));
    assert!(text.contains("imports dependencies missing from root"));
    assert!(text.contains("does not overwrite or remove the feature selection"));
    assert!(text.contains("Agent workflow"));
    assert!(text.contains("Do not assume a repository is standard or monorepo"));
}

#[test]
fn sync_all_dependencies_updates_a_standard_repository_root() {
    let repository = tempfile::tempdir().expect("temporary repository should be created");
    create_test_workspace(repository.path(), "xtask");
    create_test_dependencies_manifest(repository.path());

    sync_all_dependencies(repository.path()).expect("dependency sync should succeed");

    let manifest = fs::read_to_string(repository.path().join("Cargo.toml"))
        .expect("workspace manifest should be readable");
    assert!(manifest.contains("version = \"2.0.0\""));
    assert_lockfile_updated_without_building(repository.path());
}

#[test]
fn sync_all_dependencies_updates_every_monorepo_subrepo() {
    let repository = tempfile::tempdir().expect("temporary repository should be created");
    create_test_dependencies_manifest(repository.path());

    for subrepo in ["backend", "frontend"] {
        create_test_workspace(
            &repository.path().join(subrepo),
            &format!("xtask-{subrepo}"),
        );
    }

    sync_all_dependencies(repository.path()).expect("dependency sync should succeed");

    for subrepo in ["backend", "frontend"] {
        let manifest = fs::read_to_string(repository.path().join(subrepo).join("Cargo.toml"))
            .expect("subrepo manifest should be readable");
        assert!(manifest.contains("version = \"2.0.0\""));
        assert_lockfile_updated_without_building(&repository.path().join(subrepo));
    }
}

#[test]
fn sync_all_dependencies_imports_missing_specs_without_feature_policy() {
    let repository = tempfile::tempdir().expect("temporary repository should be created");
    create_test_workspace(repository.path(), "xtask");
    create_test_dependencies_manifest(repository.path());

    let manifest_path = repository.path().join("Cargo.toml");
    let manifest = fs::read_to_string(&manifest_path).expect("manifest should be readable");
    fs::write(
        &manifest_path,
        manifest.replace(
            "[workspace.dependencies]\n",
            r#"[workspace.dependencies]
imported-dependency = { version = "3.2.1", path = "deps/imported-dependency", features = ["extra"], default-features = false }
"#,
        ),
    )
    .expect("manifest should be updated");
    fs::create_dir_all(repository.path().join("deps/imported-dependency/src"))
        .expect("imported dependency source directory should be created");
    fs::write(
        repository
            .path()
            .join("deps/imported-dependency/Cargo.toml"),
        r#"[package]
name = "imported-dependency"
version = "3.2.1"
edition = "2024"

[features]
extra = []
"#,
    )
    .expect("imported dependency manifest should be written");
    fs::write(
        repository
            .path()
            .join("deps/imported-dependency/src/lib.rs"),
        "",
    )
    .expect("imported dependency source should be written");

    sync_all_dependencies(repository.path()).expect("dependency sync should succeed");

    let dependencies = fs::read_to_string(repository.path().join("Dependencies.toml"))
        .expect("dependencies manifest should be readable")
        .parse::<toml_edit::DocumentMut>()
        .expect("dependencies manifest should be valid TOML");
    let imported = dependencies["workspace"]["dependencies"]["imported-dependency"]
        .as_inline_table()
        .expect("path dependency should use an inline table");
    assert_eq!(
        imported.get("version").and_then(|value| value.as_str()),
        Some("3.2.1")
    );
    assert_eq!(
        imported.get("path").and_then(|value| value.as_str()),
        Some("deps/imported-dependency")
    );
    assert!(imported.get("features").is_none());
    assert!(imported.get("default-features").is_none());
}

#[test]
fn two_way_sync_rebases_imported_subrepo_paths_to_the_repository_root() {
    let repository = tempfile::tempdir().expect("temporary repository should be created");
    create_test_dependencies_manifest(repository.path());
    let backend = repository.path().join("backend");
    create_test_workspace(&backend, "xtask-backend");

    let manifest_path = backend.join("Cargo.toml");
    let manifest = fs::read_to_string(&manifest_path).expect("manifest should be readable");
    fs::write(
        &manifest_path,
        manifest.replace(
            "[workspace.dependencies]\n",
            r#"[workspace.dependencies]
local-dependency = { path = "../shared/local-dependency", features = ["local-feature"] }
version-only-dependency = { version = "4.5.6", features = ["derive"] }
"#,
        ),
    )
    .expect("manifest should be updated");

    let report = deps::sync_subrepos_two_way(
        &repository.path().join("Dependencies.toml"),
        std::slice::from_ref(&backend),
    )
    .expect("two-way dependency sync should succeed");

    assert_eq!(
        report.added_canonical_dependencies,
        vec!["local-dependency", "version-only-dependency"]
    );
    let dependencies = fs::read_to_string(repository.path().join("Dependencies.toml"))
        .expect("dependencies manifest should be readable")
        .parse::<toml_edit::DocumentMut>()
        .expect("dependencies manifest should be valid TOML");
    let imported = dependencies["workspace"]["dependencies"]["local-dependency"]
        .as_inline_table()
        .expect("path dependency should use an inline table");
    assert_eq!(
        imported.get("path").and_then(|value| value.as_str()),
        Some("shared/local-dependency")
    );
    assert!(imported.get("features").is_none());
    assert_eq!(
        dependencies["workspace"]["dependencies"]["version-only-dependency"].as_str(),
        Some("4.5.6")
    );

    let synced_subrepo = fs::read_to_string(&manifest_path)
        .expect("synced subrepo manifest should be readable")
        .parse::<toml_edit::DocumentMut>()
        .expect("synced subrepo manifest should be valid TOML");
    let local_spec = synced_subrepo["workspace"]["dependencies"]["local-dependency"]
        .as_inline_table()
        .expect("local path dependency should stay inline");
    let version_spec = synced_subrepo["workspace"]["dependencies"]["version-only-dependency"]
        .as_inline_table()
        .expect("local version dependency should stay inline");
    assert!(local_spec.get("features").is_some());
    assert!(version_spec.get("features").is_some());
}

#[test]
fn automatic_one_way_sync_does_not_import_missing_dependencies() {
    let repository = tempfile::tempdir().expect("temporary repository should be created");
    create_test_dependencies_manifest(repository.path());
    create_test_workspace(repository.path(), "xtask");

    let manifest_path = repository.path().join("Cargo.toml");
    let manifest = fs::read_to_string(&manifest_path).expect("manifest should be readable");
    fs::write(
        &manifest_path,
        manifest.replace(
            "[workspace.dependencies]\n",
            "[workspace.dependencies]\nlocal-only = \"1.2.3\"\n",
        ),
    )
    .expect("manifest should be updated");

    let report = deps::sync_subrepos(
        &repository.path().join("Dependencies.toml"),
        &[repository.path().to_path_buf()],
    )
    .expect("one-way dependency sync should succeed");

    assert!(report.added_canonical_dependencies.is_empty());
    let dependencies = fs::read_to_string(repository.path().join("Dependencies.toml"))
        .expect("dependencies manifest should be readable");
    assert!(!dependencies.contains("local-only"));
}

#[test]
fn shorthand_uses_first_letter_of_each_name_segment() {
    assert_eq!(subrepo_shorthand("product-backend").as_deref(), Some("pb"));
    assert_eq!(
        subrepo_shorthand("burn-central-app").as_deref(),
        Some("bca")
    );
}

#[test]
fn shorthand_ignores_repeated_separators() {
    assert_eq!(subrepo_shorthand("product--backend").as_deref(), Some("pb"));
    assert_eq!(subrepo_shorthand("product_backend").as_deref(), Some("pb"));
    assert_eq!(subrepo_shorthand("product.backend").as_deref(), Some("pb"));
}

#[test]
fn exact_selector_matches_subrepo_name() {
    let subrepos = vec![workspace("product-backend"), workspace("frontend")];

    assert_eq!(
        select(&subrepos, "product-backend").expect("selector should match exact subrepo"),
        "product-backend"
    );
}

#[test]
fn prefix_selector_matches_unambiguous_prefix() {
    let subrepos = vec![workspace("product-backend"), workspace("frontend")];

    assert_eq!(
        select(&subrepos, "product").expect("selector should match prefix"),
        "product-backend"
    );
}

#[test]
fn prefix_selector_stays_ambiguous_before_trying_shorthand() {
    let subrepos = vec![
        workspace("product-backend"),
        workspace("product-frontend"),
        workspace("platform-build"),
    ];

    let err = select(&subrepos, "p").expect_err("selector should be ambiguous");

    assert!(err.contains("Ambiguous subrepo selector 'p'"));
    assert!(err.contains("product-backend"));
    assert!(err.contains("product-frontend"));
    assert!(err.contains("platform-build"));
}

#[test]
fn shorthand_selector_matches_unambiguous_shorthand() {
    let subrepos = vec![workspace("product-backend"), workspace("frontend")];

    assert_eq!(
        select(&subrepos, "pb").expect("selector should match shorthand"),
        "product-backend"
    );
}

#[test]
fn shorthand_selector_is_case_insensitive() {
    let subrepos = vec![workspace("product-backend"), workspace("frontend")];

    assert_eq!(
        select(&subrepos, "PB").expect("selector should match shorthand case-insensitively"),
        "product-backend"
    );
}

#[test]
fn shorthand_selector_fails_when_ambiguous() {
    let subrepos = vec![workspace("product-backend"), workspace("payment-broker")];

    let err = select(&subrepos, "pb").expect_err("shorthand selector should be ambiguous");

    assert!(err.contains("Ambiguous subrepo shorthand selector 'pb'"));
    assert!(err.contains("product-backend (:pb)"));
    assert!(err.contains("payment-broker (:pb)"));
}

#[test]
fn selector_fails_when_no_exact_prefix_or_shorthand_match_exists() {
    let subrepos = vec![workspace("product-backend"), workspace("frontend")];

    let err = select(&subrepos, "unknown").expect_err("selector should not match");

    assert_eq!(err, "No subrepo matches selector 'unknown'.");
}

#[test]
fn exact_selector_takes_precedence_over_prefix() {
    let subrepos = vec![workspace("product"), workspace("product-backend")];

    assert_eq!(
        select(&subrepos, "product").expect("selector should match exact subrepo"),
        "product"
    );
}

#[test]
fn emoji_for_subrepo_supports_domain_keywords() {
    assert_eq!(emojis::emoji_for_subrepo("finance"), Some("💰"));
    assert_eq!(emojis::emoji_for_subrepo("gallery"), Some("🖼️"));
    assert_eq!(emojis::emoji_for_subrepo("stack"), Some("🧱"));
}

#[test]
fn emoji_for_subrepo_matches_keyword_inside_subrepo_name() {
    assert_eq!(emojis::emoji_for_subrepo("tracel-finance-api"), Some("💰"));
    assert_eq!(emojis::emoji_for_subrepo("shared-gallery-ui"), Some("🖼️"));
    assert_eq!(emojis::emoji_for_subrepo("fullstack-worker"), Some("🧱"));
}

#[test]
fn emoji_for_subrepo_prefers_the_longest_matching_keyword() {
    assert_eq!(emojis::emoji_for_subrepo("api-finance"), Some("💰"));
    assert_eq!(emojis::emoji_for_subrepo("console-frontend"), Some("🖥️"));
}
