mod commands;

use tracel_xtask::{init_xtask, prelude::*};

#[macro_use]
extern crate log;

#[macros::base_commands(
    Bump,
    Build,
    Check,
    Compile,
    Coverage,
    Doc,
    DockerCompose,
    Dependencies,
    Fix,
    Publish,
    Test,
    Validate,
    Vulnerabilities
)]
pub enum Command {
    /// Example of a new command which extends a base command arguments which has no subcommand.
    ExtendedBuildArgs(commands::extended_build_args::ExtendedBuildArgsCmdArgs),
    /// Example of a new command which extends a base command arguments
    ExtendedBuildNewSubCommands(
        commands::extended_build_new_sub_commands::ExtendedBuildSubCommandsCmdArgs,
    ),
    /// Example of a new command which extends sub commands of a base command.
    ExtendedCheckSubCommands(commands::extended_check_sub_commands::ExtendedCheckArgsCmdArgs),
    /// Example of a new command which extendeds target
    ExtendedTarget(commands::extended_target::ExtendedTargetCmdArgs),
    /// Example of a new command which extends a base command arguments which has subcommands.
    ExtendedTestArgs(commands::extended_test_args::ExtendedTestArgsCmdArgs),
    /// Comprehensive example of an extended Fix command with an additional target and subcommand
    ExtendedFix(commands::fix::ExtendedFixCmdArgs),
    /// Example of a new command with support of base Target
    MyCommand(commands::my_command::MyCommandCmdArgs),
    /// Example of a new command with subcommands
    MyCommandWithSubCommand(
        commands::my_command_with_sub_commands::MyCommandWithSubCommandsCmdArgs,
    ),
}

fn main() -> anyhow::Result<()> {
    let (args, environment) = init_xtask::<Command>(parse_args::<Command>()?)?;
    match args.command {
        Command::ExtendedBuildArgs(cmd_args) => {
            commands::extended_build_args::handle_command(cmd_args, environment, args.context)
        }
        Command::ExtendedBuildNewSubCommands(cmd_args) => {
            commands::extended_build_new_sub_commands::handle_command(
                cmd_args,
                environment,
                args.context,
            )
        }
        Command::ExtendedCheckSubCommands(cmd_args) => {
            commands::extended_check_sub_commands::handle_command(cmd_args)
        }
        Command::ExtendedTestArgs(cmd_args) => {
            commands::extended_test_args::handle_command(cmd_args, environment)
        }
        Command::ExtendedFix(cmd_args) => commands::fix::handle_command(cmd_args, None),
        Command::ExtendedTarget(cmd_args) => commands::extended_target::handle_command(cmd_args),
        Command::MyCommand(cmd_args) => commands::my_command::handle_command(cmd_args),
        Command::MyCommandWithSubCommand(cmd_args) => {
            commands::my_command_with_sub_commands::handle_command(cmd_args)
        }
        // dispatch_base_commands function is generated by the base_commands macro
        _ => dispatch_base_commands(args, environment),
    }?;
    Ok(())
}
